version: "3.8"
services:
  webserver:
    build: webserver/
    ports:
      - "8080:8080"
    volumes:
      - ./webserver/uploads:/usr/src/app/uploads
  gltf-to-usdz-service:
    image: marlon360/gltf-to-usdz-service:latest
    volumes:
      - ./webserver/uploads:/usr/app